- hosts: web
  become: yes
  tasks:
    - name: Docker login
      shell: echo "{{ docker_password }}" | docker login -u "{{ docker_username }}" --password-stdin
      vars:
        docker_username: 02fe22bcs177
        docker_password: Wilfred01@#$

  
    - name: Stop existing container
      shell: docker rm -f myapp || true

    - name: Pull latest Docker image
      shell: docker pull 02fe22bcs177/myapp:latest

    - name: Copy .env file to EC2
      copy:
        src: .env
        dest: /home/ec2-user/my-portfolio-app/.env

    - name: Create uploads directory
      file:
        path: /home/ec2-user/my-portfolio-app/uploads
        state: directory
        mode: '0755'


    - name: Run Docker container
      shell: docker run -d -p 3000:3000 --name myapp --env-file /home/ec2-user/.env 02fe22bcs177/myapp:latest
